version: 2.1
jobs:
  test:
    docker:
      - image: openjdk:8u342
    steps:
      - checkout
      - when:
          condition:
            equal: [ ci ]
          steps:
            - run:
                name: The First Step
                command: |
                  ls
