version: 2.1
jobs:
  test:
    docker:
      - image: openjdk:8u342
    steps:
      - checkout
      - run:
          name: test
          command: |
            ./gradlew tasks
            export PUB_VERSION=$(VERSION_SCOPE='' ./gradlew currentVersion -q)
            echo "Check version[${PUB_VERSION}] and tag"
            bash -c '! (git tag | grep "^${PUB_VERSION}$")'

workflows:
  version: 2
  test:
    jobs:
      - test