version: 2.1
jobs:
  test:
    docker:
      - image: openjdk:8u342
    steps:
      - checkout
      - run:
          name: test
          command: |
            ./gradlew tasks
            export PUB_VERSION=$(VERSION_SCOPE='' ./gradlew currentVersion -q)
            echo "Check version[${PUB_VERSION}] and tag"
            bash -c '! (git tag | grep "^${PUB_VERSION}$")'
            echo $GPG_KEY | base64 --decode > ${SIGNING_SECRETKEYRINGFILE}
            ./gradlew -Dorg.gradle.project.signing.keyId="$SIGNING_KEYID" -Dorg.gradle.project.signing.password="$SIGNING_PASSWORD" -Dorg.gradle.project.signing.secretKeyRingFile="$SIGNING_SECRETKEYRINGFILE" check build coveralls

workflows:
  version: 2
  test:
    jobs:
      - test