version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:8u342
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            ls
            git status
#      - when:
#          condition:
#            equal: [ ci ]
#          steps:
#            - run:
#                name: The First Step
#                command: |
#                  ls
#                  git status
